openapi: 3.0.0
info:
  title: UPCAST Publish Plugin API
  version: 0.1.0
paths:
  /catalog/create_dataset/:
    post:
      summary: Create Dataset
      operationId: create_dataset_catalog_create_dataset__post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: >-
                #/components/schemas/Body_create_dataset_catalog_create_dataset__post
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /catalog/create_dataset_from_resource_spec/:
    post:
      summary: Create Dataset From Resource Spec
      operationId: >-
        create_dataset_from_resource_spec_catalog_create_dataset_from_resource_spec__post
      parameters:
        - name: organization_name
          in: query
          required: true
          schema:
            type: string
            title: Organization Name
      requestBody:
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: >-
                    #/components/schemas/Body_create_dataset_from_resource_spec_catalog_create_dataset_from_resource_spec__post
              title: Body
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /catalog/update_dataset/:
    post:
      summary: Update Dataset
      operationId: update_dataset_catalog_update_dataset__post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: >-
                #/components/schemas/Body_update_dataset_catalog_update_dataset__post
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /catalog/delete_dataset/:
    post:
      summary: Delete Dataset
      operationId: delete_dataset_catalog_delete_dataset__post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: >-
                #/components/schemas/Body_delete_dataset_catalog_delete_dataset__post
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /catalog/upload_data/:
    post:
      summary: Upload File
      operationId: upload_file_catalog_upload_data__post
      parameters:
        - name: dataset_id
          in: query
          required: true
          schema:
            type: string
            title: Dataset Id
      requestBody:
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: >-
                    #/components/schemas/Body_upload_file_catalog_upload_data__post
              title: Body
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_create_dataset_catalog_create_dataset__post:
      properties:
        package_name:
          type: string
          title: Package Name
        package_title:
          type: string
          title: Package Title
        organization_name:
          type: string
          title: Organization Name
        package_notes:
          type: string
          title: Package Notes
      type: object
      required:
        - package_name
        - package_title
        - organization_name
        - package_notes
      title: Body_create_dataset_catalog_create_dataset__post
    Body_create_dataset_from_resource_spec_catalog_create_dataset_from_resource_spec__post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      title: >-
        Body_create_dataset_from_resource_spec_catalog_create_dataset_from_resource_spec__post
    Body_delete_dataset_catalog_delete_dataset__post:
      properties:
        package_id:
          type: string
          title: Package Id
      type: object
      required:
        - package_id
      title: Body_delete_dataset_catalog_delete_dataset__post
    Body_update_dataset_catalog_update_dataset__post:
      properties:
        package_id:
          type: string
          title: Package Id
        package_name:
          type: string
          title: Package Name
        package_title:
          type: string
          title: Package Title
        organization_name:
          type: string
          title: Organization Name
        package_notes:
          type: string
          title: Package Notes
      type: object
      required:
        - package_id
        - package_name
        - package_title
        - organization_name
        - package_notes
      title: Body_update_dataset_catalog_update_dataset__post
    Body_upload_file_catalog_upload_data__post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      title: Body_upload_file_catalog_upload_data__post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
